python bayesian_opt.py \
  --task_name "sst2" \
  --n_prompt_tokens 50 \
  --intrinsic_dim 20 \
  --k_shot 16 \
  --device "cuda:0" \
  --seed 42 \
  --loss_type "ce" \
  --cat_or_add "add" \
  --budget 8000 \
  --print_every 10 \
  --eval_every 10
